import { useCallback, useEffect, useId, useRef, useState } from 'react';
import { AlertTriangle, FileText, Info, Loader2, Play, RefreshCw, Square } from 'lucide-react';
import { defineMessages, useIntl } from '../../i18n';
import { COMPETITION_CATALOG } from '../../catalog/competitionRules';
import type { WorkspaceEntry } from '../../types/workspaceApi';
import { describeError, type IpcError, type IpcResult } from '../../utils/ipcResult';
import {
  compareReviews,
  type DimensionName,
  type ReviewComparison,
  type ReviewRecord,
  type ReviewSuggestion,
} from '../../utils/review/reviewModel';
import { reviewPaperFormat } from '../../utils/review/reviewRecord';
import { acpReviewKernel } from '../../utils/review/reviewAcp';
import {
  REVIEW_TIMEOUT_MS,
  startReview,
  type ReviewFailure,
  type ReviewRun,
} from '../../utils/review/reviewRunner';
import type { WorkspaceFeaturePanelProps, WorkspaceFileLocation } from './featurePanelProps';

const messages = defineMessages({
  title: { id: 'review.title', defaultMessage: 'Mock review' },
  disclaimer: {
    id: 'review.disclaimer',
    defaultMessage: 'Review results are generated by a model and are for reference only.',
  },
  paper: { id: 'review.paper', defaultMessage: 'Paper' },
  paperPlaceholder: { id: 'review.paperPlaceholder', defaultMessage: 'Choose a paper' },
  noPapers: {
    id: 'review.noPapers',
    defaultMessage: 'No LaTeX, Markdown or PDF paper was found in this project.',
  },
  refreshPapers: { id: 'review.refreshPapers', defaultMessage: 'Refresh the paper list' },
  papersFailed: {
    id: 'review.papersFailed',
    defaultMessage: 'Could not list the papers in this project: {detail}',
  },
  competition: { id: 'review.competition', defaultMessage: 'Competition' },
  competitionPlaceholder: {
    id: 'review.competitionPlaceholder',
    defaultMessage: 'Choose a competition',
  },
  start: { id: 'review.start', defaultMessage: 'Start review' },
  cancel: { id: 'review.cancel', defaultMessage: 'Stop review' },
  checking: { id: 'review.checking', defaultMessage: 'Checking the paper file…' },
  running: {
    id: 'review.running',
    defaultMessage:
      'Reviewing {paper}. This can take several minutes; you can switch tabs meanwhile.',
  },
  saving: { id: 'review.saving', defaultMessage: 'Saving the review…' },
  notStarted: { id: 'review.notStarted', defaultMessage: 'The review was not started' },
  errorNoCompetition: {
    id: 'review.errorNoCompetition',
    defaultMessage:
      'No competition is selected. Choose the competition whose criteria the review should follow.',
  },
  errorNoPaper: {
    id: 'review.errorNoPaper',
    defaultMessage: 'No paper is selected. Choose the paper file to review.',
  },
  errorPaperNotFound: {
    id: 'review.errorPaperNotFound',
    defaultMessage: 'The paper file does not exist: {paper}',
  },
  errorPaperUnreadable: {
    id: 'review.errorPaperUnreadable',
    defaultMessage: 'The paper file cannot be read: {paper}',
  },
  errorPaperEmpty: {
    id: 'review.errorPaperEmpty',
    defaultMessage: 'The paper file is empty: {paper}',
  },
  errorUnsupported: {
    id: 'review.errorUnsupported',
    defaultMessage: 'Only LaTeX (.tex), Markdown (.md) and PDF files can be reviewed.',
  },
  errorOutsideProject: {
    id: 'review.errorOutsideProject',
    defaultMessage: 'The paper must be a file inside the current project.',
  },
  errorCheckFailed: {
    id: 'review.errorCheckFailed',
    defaultMessage: 'Could not check the paper file: {detail}',
  },
  incompleteTitle: { id: 'review.incompleteTitle', defaultMessage: 'Review incomplete' },
  incompleteNote: {
    id: 'review.incompleteNote',
    defaultMessage: 'This result was not saved, and earlier reviews of this paper are unchanged.',
  },
  failureKernelUnavailable: {
    id: 'review.failureKernelUnavailable',
    defaultMessage: 'The Kernel is not available: {detail}',
  },
  failureSessionFailed: {
    id: 'review.failureSessionFailed',
    defaultMessage: 'Could not start a review session in the Kernel: {detail}',
  },
  failureModelCall: {
    id: 'review.failureModelCall',
    defaultMessage: 'The model call failed: {detail}',
  },
  failureTimeout: {
    id: 'review.failureTimeout',
    defaultMessage: 'The review did not finish within {minutes} minutes.',
  },
  failureCancelled: {
    id: 'review.failureCancelled',
    defaultMessage: 'The review was interrupted.',
  },
  failureApproval: {
    id: 'review.failureApproval',
    defaultMessage:
      'The review stopped because the Kernel asked a question this panel cannot answer, such as a form from an extension. Tool approvals are refused automatically and do not stop the review. Try again.',
  },
  failureTruncated: {
    id: 'review.failureTruncated',
    defaultMessage: 'The model stopped before finishing its reply.',
  },
  failureRefused: {
    id: 'review.failureRefused',
    defaultMessage: 'The model declined to review this paper.',
  },
  failureNoJson: {
    id: 'review.failureNoJson',
    defaultMessage: 'The model reply did not contain a review result.',
  },
  failureInvalid: {
    id: 'review.failureInvalid',
    defaultMessage: 'The model reply did not match the review format ({count} problems found).',
  },
  details: { id: 'review.details', defaultMessage: 'Details' },
  saveFailed: {
    id: 'review.saveFailed',
    defaultMessage: 'The review finished but could not be saved: {detail}',
  },
  historyFailed: {
    id: 'review.historyFailed',
    defaultMessage: 'Earlier reviews of this paper could not be loaded: {detail}',
  },
  latestSaved: { id: 'review.latestSaved', defaultMessage: 'Last saved review' },
  thisReview: { id: 'review.thisReview', defaultMessage: 'New review' },
  completedAt: { id: 'review.completedAt', defaultMessage: 'Completed {time} · {competition}' },
  firstReview: {
    id: 'review.firstReview',
    defaultMessage: 'This is the first review of this paper, so no comparison is shown.',
  },
  comparisonTitle: { id: 'review.comparisonTitle', defaultMessage: 'Change since the last review' },
  comparedWith: {
    id: 'review.comparedWith',
    defaultMessage: 'Compared with the review completed {time}',
  },
  columnDimension: { id: 'review.columnDimension', defaultMessage: 'Dimension' },
  columnPrevious: { id: 'review.columnPrevious', defaultMessage: 'Previous' },
  columnCurrent: { id: 'review.columnCurrent', defaultMessage: 'This time' },
  columnDelta: { id: 'review.columnDelta', defaultMessage: 'Change' },
  scores: { id: 'review.scores', defaultMessage: 'Scores and reasons' },
  score: { id: 'review.score', defaultMessage: '{score} / 10' },
  suggestions: { id: 'review.suggestions', defaultMessage: 'Suggestions' },
  noSuggestions: { id: 'review.noSuggestions', defaultMessage: 'The model gave no suggestions.' },
  locationLines: { id: 'review.locationLines', defaultMessage: '{section} · lines {start}–{end}' },
  locationPage: { id: 'review.locationPage', defaultMessage: '{section} · page {page}' },
  openLocation: { id: 'review.openLocation', defaultMessage: 'Open in the editor: {location}' },
  sessionTitle: { id: 'review.sessionTitle', defaultMessage: 'Mock review: {paper}' },
  dimensionProblemAnalysis: {
    id: 'review.dimensionProblemAnalysis',
    defaultMessage: 'Problem analysis',
  },
  dimensionAssumptions: { id: 'review.dimensionAssumptions', defaultMessage: 'Model assumptions' },
  dimensionModelBuilding: { id: 'review.dimensionModelBuilding', defaultMessage: 'Model building' },
  dimensionSolution: { id: 'review.dimensionSolution', defaultMessage: 'Solution and results' },
  dimensionSensitivity: {
    id: 'review.dimensionSensitivity',
    defaultMessage: 'Sensitivity analysis',
  },
  dimensionWriting: { id: 'review.dimensionWriting', defaultMessage: 'Writing' },
});

type Message = (typeof messages)[keyof typeof messages];

const DIMENSION_LABELS: Record<DimensionName, Message> = {
  问题分析: messages.dimensionProblemAnalysis,
  模型假设: messages.dimensionAssumptions,
  模型建立: messages.dimensionModelBuilding,
  求解与结果: messages.dimensionSolution,
  灵敏度分析: messages.dimensionSensitivity,
  写作表达: messages.dimensionWriting,
};

const COMPETITIONS = COMPETITION_CATALOG.competitions;

/** Failures whose `detail` is the model's own text, shown under "Details". */
const REPLY_FAILURES: ReadonlySet<ReviewFailure['kind']> = new Set<ReviewFailure['kind']>([
  'no-json',
  'refused',
  'output-truncated',
  'invalid-output',
]);

const control =
  'rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring-info transition-colors motion-reduce:transition-none disabled:cursor-not-allowed disabled:opacity-50';
const field =
  'mt-1 w-full rounded-md border border-border-primary bg-background-primary px-2 py-1.5 text-xs text-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring-info disabled:opacity-50';

interface PaperOption {
  relativePath: string;
  entry: WorkspaceEntry;
}

type PaperList =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'ready'; papers: PaperOption[] }
  | { status: 'error'; detail: string };

type Phase = 'idle' | 'checking' | 'running' | 'saving';

interface ShownReview {
  record: ReviewRecord;
  comparison: ReviewComparison;
  /** A review that just finished, or the latest one saved earlier. */
  source: 'new' | 'saved';
  /** Set when a finished review could not be written. */
  saveError?: string;
}

/** An IPC call that rejects (for example a missing handler) becomes an ordinary failure. */
async function settle<T>(call: () => Promise<IpcResult<T>>): Promise<IpcResult<T>> {
  try {
    return await call();
  } catch (error) {
    return { ok: false, error: { code: 'IPC_FAILED', message: describeError(error) } };
  }
}

function competitionName(id: string): string {
  return COMPETITIONS.find((competition) => competition.id === id)?.name ?? id;
}

function suggestionLocation(suggestion: ReviewSuggestion): WorkspaceFileLocation | undefined {
  const { lines, page } = suggestion.location;
  if (lines) return { line: lines[0] };
  if (page !== undefined) return { page };
  return undefined;
}

/**
 * Mock review tab (requirement 19, task 26.5): pick a paper and a competition, run the review
 * through the Kernel, and show the scores, reasons, located suggestions and the per-dimension
 * change since the previous completed review. The disclaimer sits above the scrolling area, so
 * it is always visible without scrolling (19.7). Keyed by project, so switching projects starts
 * from a clean state and stops a running review.
 */
export default function ReviewPanel(props: WorkspaceFeaturePanelProps) {
  return <ReviewPanelBody key={props.workingDir} {...props} />;
}

function ReviewPanelBody({ workingDir, active, onOpenFile }: WorkspaceFeaturePanelProps) {
  const intl = useIntl();
  const [papers, setPapers] = useState<PaperList>({ status: 'idle' });
  const [paperPath, setPaperPath] = useState('');
  const [competitionId, setCompetitionId] = useState('');
  const [phase, setPhase] = useState<Phase>('idle');
  const [runningPaper, setRunningPaper] = useState('');
  const [startError, setStartError] = useState<string | null>(null);
  const [failure, setFailure] = useState<ReviewFailure | null>(null);
  const [historyError, setHistoryError] = useState<string | null>(null);
  const [shown, setShown] = useState<ShownReview | null>(null);
  const mounted = useRef(true);
  const runRef = useRef<ReviewRun | null>(null);
  /** Guards against a second start before the disabled button re-renders. */
  const starting = useRef(false);
  const paperSelectId = useId();
  const competitionSelectId = useId();
  const busy = phase !== 'idle';

  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      runRef.current?.cancel();
      runRef.current = null;
    };
  }, []);

  const loadPapers = useCallback(async () => {
    setPapers({ status: 'loading' });
    try {
      const snapshot = await window.electron.workspaceScanProject(workingDir);
      if (!mounted.current) return;
      const options = snapshot.artifacts
        .filter((file) => file.stage === 'paper' && reviewPaperFormat(file.relativePath) !== null)
        .map((file) => ({ relativePath: file.relativePath, entry: file }))
        .sort((a, b) => a.relativePath.localeCompare(b.relativePath));
      setPapers({ status: 'ready', papers: options });
      setPaperPath((current) => {
        if (options.some((option) => option.relativePath === current)) return current;
        return options.length === 1 ? options[0].relativePath : '';
      });
    } catch (error) {
      if (mounted.current) setPapers({ status: 'error', detail: describeError(error) });
    }
  }, [workingDir]);

  useEffect(() => {
    if (active && papers.status === 'idle') void loadPapers();
  }, [active, papers.status, loadPapers]);

  // The latest saved review of the selected paper, with its own comparison (19.3, 19.4).
  useEffect(() => {
    setShown(null);
    setHistoryError(null);
    setStartError(null);
    setFailure(null);
    if (!paperPath) return undefined;
    let current = true;
    void settle(() => window.electron.reviewList({ projectDir: workingDir, paperPath })).then(
      (result) => {
        if (!current) return;
        if (!result.ok) {
          setHistoryError(result.error.message);
          return;
        }
        const latest = result.data[result.data.length - 1];
        if (latest) {
          const comparison = compareReviews(latest, result.data);
          setShown({ record: latest, comparison, source: 'saved' });
        }
      }
    );
    return () => {
      current = false;
    };
  }, [workingDir, paperPath]);

  const paperErrorText = (error: IpcError, paper: string): string => {
    switch (error.code) {
      case 'PAPER_NOT_FOUND':
        return intl.formatMessage(messages.errorPaperNotFound, { paper });
      case 'PAPER_UNREADABLE':
        return intl.formatMessage(messages.errorPaperUnreadable, { paper });
      case 'PAPER_EMPTY':
        return intl.formatMessage(messages.errorPaperEmpty, { paper });
      case 'UNSUPPORTED_FORMAT':
        return intl.formatMessage(messages.errorUnsupported);
      case 'OUTSIDE_PROJECT':
        return intl.formatMessage(messages.errorOutsideProject);
      default:
        return intl.formatMessage(messages.errorCheckFailed, { detail: error.message });
    }
  };

  const start = async () => {
    if (busy || starting.current) return;
    setStartError(null);
    setFailure(null);
    // Requirement 19.5: say exactly why the review cannot start.
    const competition = COMPETITIONS.find((entry) => entry.id === competitionId);
    if (!competition) {
      setStartError(intl.formatMessage(messages.errorNoCompetition));
      return;
    }
    if (!paperPath) {
      setStartError(intl.formatMessage(messages.errorNoPaper));
      return;
    }
    starting.current = true;
    try {
      await runAndSave(competition.id, competition.name);
    } finally {
      starting.current = false;
    }
  };

  const runAndSave = async (competitionKey: string, competitionLabel: string) => {
    setPhase('checking');
    const check = await settle(() =>
      window.electron.reviewPaperCheck({ projectDir: workingDir, paperPath })
    );
    if (!mounted.current) return;
    if (!check.ok) {
      setStartError(paperErrorText(check.error, paperPath));
      setPhase('idle');
      return;
    }
    const paper = check.data;
    const earlier = await settle(() =>
      window.electron.reviewList({ projectDir: workingDir, paperPath: paper.paperPath })
    );
    if (!mounted.current) return;
    setHistoryError(earlier.ok ? null : earlier.error.message);
    const history = earlier.ok ? earlier.data : [];

    setShown(null);
    setRunningPaper(paper.paperPath);
    setPhase('running');
    const run = startReview(
      {
        workingDir,
        paperPath: paper.paperPath,
        format: paper.format,
        competitionId: competitionKey,
        competitionName: competitionLabel,
        sessionTitle: intl.formatMessage(messages.sessionTitle, { paper: paper.paperPath }),
      },
      acpReviewKernel
    );
    runRef.current = run;
    const outcome = await run.result;
    if (runRef.current !== run) return;
    runRef.current = null;
    if (!outcome.ok) {
      // Requirement 19.6: nothing is saved and earlier records stay as they are.
      setFailure(outcome.failure);
      setPhase('idle');
      return;
    }

    setPhase('saving');
    const saved = await settle(() =>
      window.electron.reviewSave({
        projectDir: workingDir,
        paperPath: paper.paperPath,
        competitionId: competitionKey,
        output: outcome.output,
      })
    );
    if (!mounted.current) return;
    if (saved.ok) {
      setShown({
        record: saved.data,
        comparison: compareReviews(saved.data, history),
        source: 'new',
      });
    } else if (saved.error.code === 'REVIEW_INCOMPLETE') {
      setFailure({ kind: 'invalid-output', detail: saved.error.message });
    } else {
      const record: ReviewRecord = {
        paper: paper.paperPath,
        competitionId: competitionKey,
        completedAt: new Date().toISOString(),
        ...outcome.output,
      };
      setShown({
        record,
        comparison: compareReviews(record, history),
        source: 'new',
        saveError: saved.error.message,
      });
    }
    setPhase('idle');
  };

  const stop = () => {
    runRef.current?.cancel();
  };

  const paperEntry = (paper: string): WorkspaceEntry => {
    const listed =
      papers.status === 'ready'
        ? papers.papers.find((option) => option.relativePath === paper)
        : undefined;
    if (listed) return listed.entry;
    const separator = workingDir.includes('\\') ? '\\' : '/';
    const root = workingDir.endsWith(separator) ? workingDir : `${workingDir}${separator}`;
    return {
      name: paper.split('/').pop() ?? paper,
      path: `${root}${paper.split('/').join(separator)}`,
      isDirectory: false,
      size: 0,
      modifiedAt: 0,
    };
  };

  const failureText = (value: ReviewFailure): string => {
    const detail = value.detail ?? '';
    switch (value.kind) {
      case 'kernel-unavailable':
        return intl.formatMessage(messages.failureKernelUnavailable, { detail });
      case 'session-failed':
        return intl.formatMessage(messages.failureSessionFailed, { detail });
      case 'model-call-failed':
        return intl.formatMessage(messages.failureModelCall, { detail });
      case 'timeout':
        return intl.formatMessage(messages.failureTimeout, {
          minutes: Math.round(REVIEW_TIMEOUT_MS / 60_000),
        });
      case 'cancelled':
        return intl.formatMessage(messages.failureCancelled);
      case 'approval-required':
        return intl.formatMessage(messages.failureApproval);
      case 'output-truncated':
        return intl.formatMessage(messages.failureTruncated);
      case 'refused':
        return intl.formatMessage(messages.failureRefused);
      case 'no-json':
        return intl.formatMessage(messages.failureNoJson);
      case 'invalid-output':
        return intl.formatMessage(messages.failureInvalid, {
          count: value.problems?.length ?? 1,
        });
    }
  };

  const failureDetails = (value: ReviewFailure): string | null => {
    if (!REPLY_FAILURES.has(value.kind)) return null;
    if (value.problems && value.problems.length > 0) {
      return value.problems
        .map((problem) => ('name' in problem ? `${problem.kind}: ${problem.name}` : problem.kind))
        .join('\n');
    }
    return value.detail ? value.detail : null;
  };

  const status =
    phase === 'checking'
      ? intl.formatMessage(messages.checking)
      : phase === 'running'
        ? intl.formatMessage(messages.running, { paper: runningPaper })
        : phase === 'saving'
          ? intl.formatMessage(messages.saving)
          : null;
  const paperOptions = papers.status === 'ready' ? papers.papers : [];
  const failureDetail = failure ? failureDetails(failure) : null;

  return (
    <section
      className="flex h-full min-h-0 flex-col text-text-primary"
      aria-label={intl.formatMessage(messages.title)}
      data-testid="review-panel"
    >
      {/* Requirement 19.7: outside the scrolling area, so no scrolling is needed to see it. */}
      <p
        role="note"
        data-testid="review-disclaimer"
        className="flex shrink-0 items-start gap-2 border-b border-border-primary bg-background-secondary px-4 py-2 text-xs font-medium leading-relaxed"
      >
        <Info aria-hidden="true" className="mt-0.5 h-3.5 w-3.5 shrink-0 text-text-warning" />
        <span>{intl.formatMessage(messages.disclaimer)}</span>
      </p>

      <div className="shrink-0 space-y-3 border-b border-border-primary px-4 py-3">
        <div className="flex items-center justify-between gap-2">
          <h2 className="text-sm font-semibold">{intl.formatMessage(messages.title)}</h2>
          <button
            type="button"
            className={`${control} p-1.5 hover:bg-background-tertiary`}
            aria-label={intl.formatMessage(messages.refreshPapers)}
            title={intl.formatMessage(messages.refreshPapers)}
            disabled={busy || papers.status === 'loading'}
            onClick={() => void loadPapers()}
          >
            <RefreshCw
              aria-hidden="true"
              className={`h-3.5 w-3.5 ${papers.status === 'loading' ? 'animate-spin motion-reduce:animate-none' : ''}`}
            />
          </button>
        </div>

        <div>
          <label htmlFor={paperSelectId} className="block text-xs text-text-secondary">
            {intl.formatMessage(messages.paper)}
          </label>
          <select
            id={paperSelectId}
            className={field}
            value={paperPath}
            disabled={busy}
            onChange={(event) => setPaperPath(event.target.value)}
          >
            <option value="">{intl.formatMessage(messages.paperPlaceholder)}</option>
            {paperOptions.map((option) => (
              <option key={option.relativePath} value={option.relativePath}>
                {option.relativePath}
              </option>
            ))}
          </select>
        </div>
        {papers.status === 'ready' && papers.papers.length === 0 && (
          <p className="text-xs leading-relaxed">{intl.formatMessage(messages.noPapers)}</p>
        )}
        {papers.status === 'error' && (
          <p role="alert" className="text-xs leading-relaxed text-text-danger">
            {intl.formatMessage(messages.papersFailed, { detail: papers.detail })}
          </p>
        )}

        <div>
          <label htmlFor={competitionSelectId} className="block text-xs text-text-secondary">
            {intl.formatMessage(messages.competition)}
          </label>
          <select
            id={competitionSelectId}
            className={field}
            value={competitionId}
            disabled={busy}
            onChange={(event) => setCompetitionId(event.target.value)}
          >
            <option value="">{intl.formatMessage(messages.competitionPlaceholder)}</option>
            {COMPETITIONS.map((competition) => (
              <option key={competition.id} value={competition.id}>
                {competition.name}
              </option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2">
          {phase === 'running' ? (
            <button
              type="button"
              className={`${control} flex items-center gap-1.5 border border-border-primary px-3 py-1.5 text-xs hover:bg-background-tertiary`}
              onClick={stop}
            >
              <Square aria-hidden="true" className="h-3.5 w-3.5" />
              {intl.formatMessage(messages.cancel)}
            </button>
          ) : (
            <button
              type="button"
              className={`${control} flex items-center gap-1.5 bg-text-primary px-3 py-1.5 text-xs text-background-primary`}
              disabled={busy}
              onClick={() => void start()}
            >
              <Play aria-hidden="true" className="h-3.5 w-3.5" />
              {intl.formatMessage(messages.start)}
            </button>
          )}
        </div>
        {status && (
          <p role="status" className="flex items-start gap-2 text-xs leading-relaxed">
            <Loader2
              aria-hidden="true"
              className="mt-0.5 h-3.5 w-3.5 shrink-0 animate-spin motion-reduce:animate-none"
            />
            {status}
          </p>
        )}
      </div>

      <div data-testid="review-body" className="min-h-0 flex-1 overflow-y-auto px-4 py-4">
        {startError && (
          <div role="alert" className="mb-4 rounded-lg border border-border-danger p-3 text-xs">
            <p className="font-medium">{intl.formatMessage(messages.notStarted)}</p>
            <p className="mt-1 leading-relaxed">{startError}</p>
          </div>
        )}
        {failure && (
          <div role="alert" className="mb-4 rounded-lg border border-border-danger p-3 text-xs">
            <p className="flex items-center gap-1.5 font-medium">
              <AlertTriangle aria-hidden="true" className="h-3.5 w-3.5 shrink-0" />
              {intl.formatMessage(messages.incompleteTitle)}
            </p>
            <p className="mt-1 leading-relaxed">{failureText(failure)}</p>
            <p className="mt-1 leading-relaxed">{intl.formatMessage(messages.incompleteNote)}</p>
            {failureDetail && (
              <details className="mt-2">
                <summary className="cursor-pointer">{intl.formatMessage(messages.details)}</summary>
                <pre className="mt-1 max-h-48 overflow-auto whitespace-pre-wrap break-all font-mono text-[11px]">
                  {failureDetail}
                </pre>
              </details>
            )}
          </div>
        )}
        {historyError && (
          <p role="status" className="mb-4 text-xs leading-relaxed">
            {intl.formatMessage(messages.historyFailed, { detail: historyError })}
          </p>
        )}
        {shown && (
          <ReviewResult
            shown={shown}
            onOpenSuggestion={(suggestion) =>
              onOpenFile(paperEntry(shown.record.paper), suggestionLocation(suggestion))
            }
          />
        )}
      </div>
    </section>
  );
}

interface ReviewResultProps {
  shown: ShownReview;
  onOpenSuggestion: (suggestion: ReviewSuggestion) => void;
}

function ReviewResult({ shown, onOpenSuggestion }: ReviewResultProps) {
  const intl = useIntl();
  const { record, comparison } = shown;
  const formatTime = (iso: string) =>
    intl.formatDate(Date.parse(iso), {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  const dimensionLabel = (name: DimensionName) => intl.formatMessage(DIMENSION_LABELS[name]);
  const locationText = (suggestion: ReviewSuggestion) => {
    const { section, lines, page } = suggestion.location;
    if (lines) {
      return intl.formatMessage(messages.locationLines, {
        section,
        start: lines[0],
        end: lines[1],
      });
    }
    return intl.formatMessage(messages.locationPage, { section, page: page ?? '' });
  };

  return (
    <article className="space-y-5" data-testid="review-result">
      <header className="space-y-1">
        <h3 className="text-sm font-semibold">
          {intl.formatMessage(shown.source === 'new' ? messages.thisReview : messages.latestSaved)}
        </h3>
        <p className="text-xs text-text-secondary">
          {intl.formatMessage(messages.completedAt, {
            time: formatTime(record.completedAt),
            competition: competitionName(record.competitionId),
          })}
        </p>
        <p className="break-all font-mono text-xs">{record.paper}</p>
        {shown.saveError && (
          <p role="alert" className="rounded-md border border-border-danger p-2 text-xs">
            {intl.formatMessage(messages.saveFailed, { detail: shown.saveError })}
          </p>
        )}
      </header>

      {comparison.firstReview ? (
        <p className="rounded-md border border-border-primary px-3 py-2 text-xs leading-relaxed">
          {intl.formatMessage(messages.firstReview)}
        </p>
      ) : (
        <section aria-label={intl.formatMessage(messages.comparisonTitle)}>
          <h4 className="text-xs font-medium">{intl.formatMessage(messages.comparisonTitle)}</h4>
          <p className="mt-1 text-xs text-text-secondary">
            {intl.formatMessage(messages.comparedWith, {
              time: formatTime(comparison.previousCompletedAt),
            })}
          </p>
          <table className="mt-2 w-full border-collapse text-xs">
            <thead>
              <tr className="border-b border-border-primary text-left">
                <th scope="col" className="py-1 pr-2 font-medium">
                  {intl.formatMessage(messages.columnDimension)}
                </th>
                <th scope="col" className="py-1 pr-2 text-right font-medium">
                  {intl.formatMessage(messages.columnPrevious)}
                </th>
                <th scope="col" className="py-1 pr-2 text-right font-medium">
                  {intl.formatMessage(messages.columnCurrent)}
                </th>
                <th scope="col" className="py-1 text-right font-medium">
                  {intl.formatMessage(messages.columnDelta)}
                </th>
              </tr>
            </thead>
            <tbody>
              {comparison.deltas.map((delta) => (
                <tr key={delta.name} className="border-b border-border-primary">
                  <th scope="row" className="py-1 pr-2 text-left font-normal">
                    {dimensionLabel(delta.name)}
                  </th>
                  <td className="py-1 pr-2 text-right tabular-nums">{delta.previous}</td>
                  <td className="py-1 pr-2 text-right tabular-nums">{delta.current}</td>
                  <td className="py-1 text-right tabular-nums">
                    {intl.formatNumber(delta.delta, { signDisplay: 'exceptZero' })}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      <section>
        <h4 className="text-xs font-medium">{intl.formatMessage(messages.scores)}</h4>
        <ol className="mt-2 space-y-3">
          {record.dimensions.map((dimension) => (
            <li key={dimension.name} className="rounded-md border border-border-primary p-2.5">
              <div className="flex items-baseline justify-between gap-2">
                <span className="text-xs font-medium">{dimensionLabel(dimension.name)}</span>
                <span className="text-xs tabular-nums">
                  {intl.formatMessage(messages.score, { score: dimension.score })}
                </span>
              </div>
              <ul className="mt-1.5 list-disc space-y-1 pl-4 text-xs leading-relaxed">
                {dimension.reasons.map((reason, index) => (
                  <li key={index}>{reason}</li>
                ))}
              </ul>
            </li>
          ))}
        </ol>
      </section>

      <section>
        <h4 className="text-xs font-medium">{intl.formatMessage(messages.suggestions)}</h4>
        {record.suggestions.length === 0 ? (
          <p className="mt-2 text-xs">{intl.formatMessage(messages.noSuggestions)}</p>
        ) : (
          <ol className="mt-2 space-y-2">
            {record.suggestions.map((suggestion, index) => {
              const location = locationText(suggestion);
              return (
                <li key={index} className="rounded-md border border-border-primary p-2.5 text-xs">
                  <p className="leading-relaxed">{suggestion.text}</p>
                  <button
                    type="button"
                    className={`${control} mt-1.5 flex items-center gap-1.5 text-left text-text-secondary hover:text-text-primary hover:underline`}
                    title={intl.formatMessage(messages.openLocation, { location })}
                    aria-label={intl.formatMessage(messages.openLocation, { location })}
                    onClick={() => onOpenSuggestion(suggestion)}
                  >
                    <FileText aria-hidden="true" className="h-3.5 w-3.5 shrink-0" />
                    <span className="break-all">{location}</span>
                  </button>
                </li>
              );
            })}
          </ol>
        )}
      </section>
    </article>
  );
}
