import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { IntlTestWrapper } from '../../i18n/test-utils';
import type { ProjectSnapshot } from '../../types/workspaceApi';
import {
  REVIEW_DIMENSIONS,
  type ReviewOutput,
  type ReviewRecord,
} from '../../utils/review/reviewModel';
import ReviewPanel from './ReviewPanel';

const kernel = vi.hoisted(() => ({
  unavailableReason: vi.fn(),
  openSession: vi.fn(),
  prompt: vi.fn(),
  cancel: vi.fn(),
  isWaitingForUser: vi.fn(),
  replyTexts: vi.fn(),
  closeSession: vi.fn(),
}));
vi.mock('../../utils/review/reviewAcp', () => ({ acpReviewKernel: kernel }));

const DISCLAIMER = 'Review results are generated by a model and are for reference only.';
const originalElectron = window.electron;
const scan = vi.fn();
const paperCheck = vi.fn();
const list = vi.fn();
const save = vi.fn();
const openFile = vi.fn();

function snapshot(): ProjectSnapshot {
  return {
    root: '/project',
    scannedAt: 1,
    limited: false,
    unreadableDirectories: 0,
    artifacts: [
      {
        name: 'main.tex',
        relativePath: 'paper/main.tex',
        path: '/project/paper/main.tex',
        isDirectory: false,
        size: 120,
        modifiedAt: 1,
        stage: 'paper',
      },
      {
        name: 'refs.bib',
        relativePath: 'paper/refs.bib',
        path: '/project/paper/refs.bib',
        isDirectory: false,
        size: 40,
        modifiedAt: 1,
        stage: 'paper',
      },
    ],
  };
}

function output(scores: number[]): ReviewOutput {
  return {
    dimensions: REVIEW_DIMENSIONS.map((name, index) => ({
      name,
      score: scores[index],
      reasons: [`${name}：理由 ${index + 1}`],
    })),
    suggestions: [
      {
        text: '问题三补充最优方案的数值表',
        location: { section: '5.3 问题三', lines: [212, 240] },
      },
    ],
  };
}

function record(completedAt: string, scores: number[]): ReviewRecord {
  return { paper: 'paper/main.tex', competitionId: 'cumcm', completedAt, ...output(scores) };
}

const panel = (active = true) => (
  <IntlTestWrapper>
    <ReviewPanel
      workingDir="/project"
      active={active}
      isAgentActive={false}
      onOpenFile={openFile}
      onCompose={vi.fn()}
    />
  </IntlTestWrapper>
);

function replyWith(reply: ReviewOutput) {
  kernel.unavailableReason.mockResolvedValue(null);
  kernel.openSession.mockResolvedValue('review-session');
  kernel.prompt.mockResolvedValue('end_turn');
  kernel.cancel.mockResolvedValue(undefined);
  kernel.isWaitingForUser.mockReturnValue(false);
  kernel.replyTexts.mockReturnValue([`\`\`\`json\n${JSON.stringify(reply)}\n\`\`\``]);
  kernel.closeSession.mockResolvedValue(undefined);
}

async function paperSelected() {
  const select = screen.getByRole('combobox', { name: 'Paper' });
  await waitFor(() => expect(select).toHaveValue('paper/main.tex'));
  return select;
}

function chooseCompetition(id = 'cumcm') {
  fireEvent.change(screen.getByRole('combobox', { name: 'Competition' }), {
    target: { value: id },
  });
}

/** The disclaimer is the panel's first child and lies outside the only scrolling area. */
function expectDisclaimerPinned() {
  const panelElement = screen.getByTestId('review-panel');
  const disclaimer = screen.getByRole('note');
  const body = screen.getByTestId('review-body');

  expect(disclaimer).toHaveTextContent(DISCLAIMER);
  expect(disclaimer).toBeVisible();
  expect(panelElement.firstElementChild).toBe(disclaimer);
  expect(body).toHaveClass('overflow-y-auto');
  expect(body.contains(disclaimer)).toBe(false);
  const position = disclaimer.compareDocumentPosition(body);
  expect(position & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
  for (let node: HTMLElement | null = disclaimer; node && node !== panelElement; ) {
    expect(node.className).not.toMatch(/overflow-(y-)?(auto|scroll)/);
    node = node.parentElement;
  }
  expect(panelElement.className).not.toMatch(/overflow-(y-)?(auto|scroll)/);
}

beforeEach(() => {
  vi.clearAllMocks();
  scan.mockResolvedValue(snapshot());
  list.mockResolvedValue({ ok: true, data: [] });
  paperCheck.mockResolvedValue({
    ok: true,
    data: { paperPath: 'paper/main.tex', format: 'latex', size: 120 },
  });
  save.mockImplementation(
    async (request: { paperPath: string; competitionId: string; output: ReviewOutput }) => ({
      ok: true,
      data: {
        paper: request.paperPath,
        competitionId: request.competitionId,
        completedAt: '2026-10-02T09:30:00.000Z',
        ...request.output,
      },
    })
  );
  window.electron = {
    ...originalElectron,
    workspaceScanProject: scan,
    reviewPaperCheck: paperCheck,
    reviewList: list,
    reviewSave: save,
  };
});

afterEach(() => {
  window.electron = originalElectron;
});

describe('ReviewPanel disclaimer (requirement 19.7)', () => {
  it('pins the disclaimer above the scrolling content before any review', async () => {
    render(panel());
    await paperSelected();
    expectDisclaimerPinned();
  });

  it('keeps the disclaimer at the top when a long result is shown', async () => {
    list.mockResolvedValue({
      ok: true,
      data: [record('2026-09-01T08:00:00.000Z', [5, 5, 5, 5, 5, 5])],
    });
    render(panel());

    const result = await screen.findByTestId('review-result');
    expect(screen.getByTestId('review-body').contains(result)).toBe(true);
    expect(screen.getByText('Last saved review')).toBeVisible();
    expectDisclaimerPinned();
  });

  it('shows the disclaimer even while the tab is hidden and has not loaded', () => {
    render(panel(false));
    expect(screen.getByRole('note')).toHaveTextContent(DISCLAIMER);
    expect(scan).not.toHaveBeenCalled();
  });
});

describe('ReviewPanel start checks (requirement 19.5)', () => {
  it('does not start without a competition and says so', async () => {
    render(panel());
    await paperSelected();
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent('No competition is selected');
    expect(paperCheck).not.toHaveBeenCalled();
    expect(kernel.openSession).not.toHaveBeenCalled();
  });

  it('only lists LaTeX, Markdown and PDF papers', async () => {
    render(panel());
    const select = await paperSelected();
    expect(within(select).getAllByRole('option').map((option) => option.textContent)).toEqual([
      'Choose a paper',
      'paper/main.tex',
    ]);
  });

  it.each([
    ['PAPER_NOT_FOUND', 'The paper file does not exist: paper/main.tex'],
    ['PAPER_UNREADABLE', 'The paper file cannot be read: paper/main.tex'],
  ])('names the reason when the check fails with %s', async (code, text) => {
    paperCheck.mockResolvedValue({ ok: false, error: { code, message: 'detail' } });
    render(panel());
    await paperSelected();
    chooseCompetition();
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent('The review was not started');
    expect(alert).toHaveTextContent(text);
    expect(kernel.openSession).not.toHaveBeenCalled();
    expect(save).not.toHaveBeenCalled();
  });
});

describe('ReviewPanel review run', () => {
  it('saves a completed review and compares every dimension with the last one', async () => {
    const previous = record('2026-09-01T08:00:00.000Z', [5, 6, 7, 4, 3, 6]);
    list.mockResolvedValue({ ok: true, data: [previous] });
    replyWith(output([7, 6, 5, 4, 5, 8]));
    render(panel());
    await paperSelected();
    await screen.findByText('Last saved review');
    chooseCompetition('cumcm');
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    expect(await screen.findByText('New review')).toBeVisible();
    expect(paperCheck).toHaveBeenCalledWith({
      projectDir: '/project',
      paperPath: 'paper/main.tex',
    });
    expect(kernel.openSession).toHaveBeenCalledWith('/project', 'Mock review: paper/main.tex');
    expect(save).toHaveBeenCalledWith({
      projectDir: '/project',
      paperPath: 'paper/main.tex',
      competitionId: 'cumcm',
      output: output([7, 6, 5, 4, 5, 8]),
    });

    const rows = within(screen.getByRole('table')).getAllByRole('row').slice(1);
    const cells = rows.map((row) =>
      within(row)
        .getAllByRole('cell')
        .map((cell) => cell.textContent)
    );
    expect(cells).toEqual([
      ['5', '7', '+2'],
      ['6', '6', '0'],
      ['7', '5', '-2'],
      ['4', '4', '0'],
      ['3', '5', '+2'],
      ['6', '8', '+2'],
    ]);
    expect(within(rows[0]).getByRole('rowheader')).toHaveTextContent('Problem analysis');
    expect(screen.getByText('问题分析：理由 1')).toBeVisible();

    fireEvent.click(
      screen.getByRole('button', { name: 'Open in the editor: 5.3 问题三 · lines 212–240' })
    );
    expect(openFile).toHaveBeenCalledWith(
      expect.objectContaining({ path: '/project/paper/main.tex' }),
      { line: 212 }
    );
    expectDisclaimerPinned();
  });

  it('marks the first review of a paper and shows no comparison (requirement 19.4)', async () => {
    replyWith(output([6, 6, 6, 6, 6, 6]));
    render(panel());
    await paperSelected();
    chooseCompetition('mcm');
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    expect(
      await screen.findByText('This is the first review of this paper, so no comparison is shown.')
    ).toBeVisible();
    expect(screen.queryByRole('table')).not.toBeInTheDocument();
  });

  it('reports an incomplete review and saves nothing (requirement 19.6)', async () => {
    replyWith(output([6, 6, 6, 6, 6, 6]));
    kernel.prompt.mockRejectedValue(new Error('provider returned 500'));
    render(panel());
    await paperSelected();
    chooseCompetition();
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent('Review incomplete');
    expect(alert).toHaveTextContent('The model call failed: provider returned 500');
    expect(alert).toHaveTextContent('This result was not saved');
    expect(save).not.toHaveBeenCalled();
    expect(kernel.closeSession).toHaveBeenCalledWith('review-session');
  });

  it('treats a reply that fails validation as incomplete', async () => {
    const broken = output([6, 6, 6, 6, 6, 6]);
    broken.dimensions[0].score = 12;
    replyWith(broken);
    render(panel());
    await paperSelected();
    chooseCompetition();
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    const alert = await screen.findByRole('alert');
    expect(alert).toHaveTextContent(
      'The model reply did not match the review format (1 problems found).'
    );
    expect(save).not.toHaveBeenCalled();
  });

  it('stops a running review', async () => {
    replyWith(output([6, 6, 6, 6, 6, 6]));
    kernel.prompt.mockReturnValue(new Promise(() => undefined));
    render(panel());
    await paperSelected();
    chooseCompetition();
    fireEvent.click(screen.getByRole('button', { name: 'Start review' }));

    fireEvent.click(await screen.findByRole('button', { name: 'Stop review' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('The review was interrupted.');
    expect(kernel.cancel).toHaveBeenCalledWith('review-session');
    expect(save).not.toHaveBeenCalled();
  });
});
