/**
 * Algorithm catalogue shown in the 扩展 → 算法 page.
 *
 * Every entry names a real, permissively licensed library so the metadata can be
 * verified: the agent installs the dependency (via `check_env` from the modeling
 * extension) and writes the code, rather than the catalogue shipping code itself.
 * Algorithm implementations themselves are not vendored, so no third-party source
 * is redistributed here.
 */
export type AlgorithmCategory =
  | 'optimization'
  | 'prediction'
  | 'classification'
  | 'clustering'
  | 'evaluation'
  | 'time-series'
  | 'dimensionality';

export interface AlgorithmEntry {
  id: string;
  /** Display name, also used as the card title. */
  name: string;
  category: AlgorithmCategory;
  /** One-line summary of what the method does. */
  summary: string;
  /** When this method is the right choice. */
  useWhen: string[];
  /** What the caller has to supply. */
  dataNeeded: string[];
  /** What comes back out. */
  outputs: string[];
  /** Situations this method handles badly. */
  notSuitableFor: string[];
  /** pip package(s) the agent should install. */
  dependencies: string[];
  /** Fully qualified symbol the agent should call. */
  entrypoint: string;
  license: string;
  /** Where the upstream project lives. */
  homepage: string;
}

export const ALGORITHM_CATEGORIES: AlgorithmCategory[] = [
  'optimization',
  'prediction',
  'time-series',
  'classification',
  'clustering',
  'dimensionality',
  'evaluation',
];

export const ALGORITHM_CATALOG: AlgorithmEntry[] = [
  {
    id: 'pso',
    name: '粒子群优化 PSO',
    category: 'optimization',
    summary: '通过群体协同搜索连续空间中的较优解，适合黑箱和非凸目标函数。',
    useWhen: ['目标函数不可导、非凸或为黑箱', '变量维数中等（10–100）', '需要快速拿到可用解而非严格最优性证明'],
    dataNeeded: ['目标函数', '变量上下界', '种群规模与终止条件（迭代数或收敛阈值）'],
    outputs: ['最优解向量', '适应度收敛曲线', '每次迭代的种群分布'],
    notSuitableFor: ['需要全局最优性证明的场景', '变量为整数或含复杂约束时需额外编码'],
    dependencies: ['mealpy'],
    entrypoint: 'mealpy.swarm_based.PSO.OriginalPSO',
    license: 'MIT',
    homepage: 'https://github.com/thieu1995/mealpy',
  },
  {
    id: 'nsga2',
    name: 'NSGA-II 多目标优化',
    category: 'optimization',
    summary: '同时优化多个相互冲突的目标，输出可供权衡选择的 Pareto 解集。',
    useWhen: ['存在两个及以上相互冲突的目标', '需要给决策者一组折中方案而非单一解'],
    dataNeeded: ['各目标函数', '变量上下界', '种群规模与迭代数'],
    outputs: ['Pareto 前沿解集', '各解的多个目标值'],
    notSuitableFor: ['目标数过多（>3）时拥挤度排序退化', '目标间不冲突时用单目标即可'],
    dependencies: ['pymoo'],
    entrypoint: 'pymoo.algorithms.moo.nsga2.NSGA2',
    license: 'Apache-2.0',
    homepage: 'https://github.com/anyoptimization/pymoo',
  },
  {
    id: 'linear-programming',
    name: '线性规划',
    category: 'optimization',
    summary: '在线性目标与线性约束下寻找最优资源配置方案。',
    useWhen: ['目标与约束都能写成线性形式', '需要可证明的最优解', '变量规模大但结构规整'],
    dataNeeded: ['目标函数系数', '约束矩阵与右端项', '变量取值范围'],
    outputs: ['最优解', '最优目标值', '约束的松弛量（影子价格）'],
    notSuitableFor: ['目标或约束含非线性、乘积项', '需要整数解时应改用整数规划'],
    dependencies: ['scipy'],
    entrypoint: 'scipy.optimize.linprog',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scipy/scipy',
  },
  {
    id: 'milp',
    name: '混合整数规划 MILP',
    category: 'optimization',
    summary: '在连续变量之外加入整数/0-1 决策变量，表达选址、排班、选址开关等离散选择。',
    useWhen: ['决策含"是否启用""选哪个"这类离散选择', '需要精确最优解而非启发式近似'],
    dataNeeded: ['连续与整数变量定义', '线性约束', '目标函数'],
    outputs: ['最优解与最优值', '求解状态（最优/不可行/超时）'],
    notSuitableFor: ['规模极大且无结构时求解时间不可控', '约束非线性'],
    dependencies: ['pulp'],
    entrypoint: 'pulp.LpProblem + pulp.LpVariable(cat="Binary")',
    license: 'MIT',
    homepage: 'https://github.com/coin-or/pulp',
  },
  {
    id: 'linear-regression',
    name: '线性回归',
    category: 'prediction',
    summary: '建立连续目标与一个或多个特征之间的线性关系，适合作为可解释基线。',
    useWhen: ['需要可解释的系数含义', '特征与目标近似线性', '样本量远大于特征数'],
    dataNeeded: ['数值特征矩阵', '连续目标值'],
    outputs: ['回归系数与截距', 'R²、RMSE、残差分布'],
    notSuitableFor: ['强非线性关系', '特征高度共线（需先做 VIF 检查或改用岭回归）'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.linear_model.LinearRegression',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'random-forest-regression',
    name: '随机森林回归',
    category: 'prediction',
    summary: '用多棵决策树捕获非线性关系，对异常值和复杂特征交互较稳健。',
    useWhen: ['关系非线性且存在特征交互', '特征量纲不一、含异常值', '需要特征重要性排序'],
    dataNeeded: ['特征矩阵（可含类别特征）', '连续目标值', '树数量与深度等超参'],
    outputs: ['预测值', '特征重要性', '袋外误差估计'],
    notSuitableFor: ['需要外推预测（树模型不能超出训练范围）', '样本极少时容易过拟合'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.ensemble.RandomForestRegressor',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'arima',
    name: 'ARIMA 时间序列预测',
    category: 'prediction',
    summary: '利用序列自身的滞后项与误差结构预测未来，适合单变量平稳化后的序列。',
    useWhen: ['单变量时间序列、有趋势或季节性', '样本按时间等间隔采集'],
    dataNeeded: ['等间隔时间序列', '差分阶数 d 与 p、q 阶数（可用 AIC 选择）'],
    outputs: ['预测值及置信区间', '残差诊断（ACF/PACF、Ljung-Box）'],
    notSuitableFor: ['多变量互相影响（改用 VAR 或带外生变量）', '非平稳且差分后仍不平稳'],
    dependencies: ['statsmodels'],
    entrypoint: 'statsmodels.tsa.arima.model.ARIMA',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/statsmodels/statsmodels',
  },
  {
    id: 'logistic-regression',
    name: '逻辑回归',
    category: 'classification',
    summary: '输出类别概率的线性分类器，系数可直接解释为对数几率。',
    useWhen: ['二分类且需要概率输出', '需要解释特征影响方向与强度'],
    dataNeeded: ['数值特征矩阵', '类别标签'],
    outputs: ['类别概率与预测类别', '系数与优势比', 'ROC/AUC'],
    notSuitableFor: ['特征与对数几率非线性', '类别极不平衡时需重采样或调 class_weight'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.linear_model.LogisticRegression',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'xgboost',
    name: 'XGBoost 梯度提升',
    category: 'classification',
    summary: '梯度提升树集成，在表格数据上通常是最强的通用模型之一。',
    useWhen: ['表格数据、特征关系复杂', '追求预测精度、可接受调参成本'],
    dataNeeded: ['特征矩阵', '标签', '学习率、树深、轮数等超参'],
    outputs: ['预测值/概率', '特征重要性', 'SHAP 解释所需的树结构'],
    notSuitableFor: ['样本量极小', '需要强可解释性且不接受后验解释'],
    dependencies: ['xgboost'],
    entrypoint: 'xgboost.XGBClassifier / xgboost.XGBRegressor',
    license: 'Apache-2.0',
    homepage: 'https://github.com/dmlc/xgboost',
  },
  {
    id: 'kmeans',
    name: 'K-Means 聚类',
    category: 'clustering',
    summary: '按距离把样本划分为 K 个簇，适合先做无监督分群再解释。',
    useWhen: ['探索性分群、无标签', '簇近似球形且规模相当'],
    dataNeeded: ['数值特征矩阵（需标准化）', '簇数 K 或选择 K 的依据（肘部法/轮廓系数）'],
    outputs: ['各样本簇标签', '簇中心', '轮廓系数'],
    notSuitableFor: ['簇形状非凸或大小差异极大', '含大量离群点（改用 DBSCAN）'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.cluster.KMeans',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'dbscan',
    name: 'DBSCAN 密度聚类',
    category: 'clustering',
    summary: '按密度连通划分簇，能识别任意形状的簇并把噪声单独标出。',
    useWhen: ['簇形状不规则', '数据含噪声或离群点', '事先不知道簇数'],
    dataNeeded: ['数值特征矩阵', '邻域半径 eps 与最小点数 minPts'],
    outputs: ['簇标签（-1 表示噪声）', '核心点/边界点划分'],
    notSuitableFor: ['各簇密度差异很大（参数难以统一）', '高维数据（距离度量失效）'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.cluster.DBSCAN',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'topsis',
    name: 'TOPSIS 综合评价',
    category: 'evaluation',
    summary: '把多指标方案按与理想解的距离排序，用于评价类赛题。',
    useWhen: ['多指标综合评价、需要方案排序', '指标量纲不同需要归一化'],
    dataNeeded: ['方案×指标的评价矩阵', '各指标权重（熵权法/AHP/主观）', '指标正负向'],
    outputs: ['各方案综合得分与排名', '与正负理想解的距离'],
    notSuitableFor: ['指标间强相关未去重时会重复计权', '需要解释指标间因果关系时'],
    dependencies: ['numpy'],
    entrypoint: '自实现（numpy 向量化，约 40 行）',
    license: '—（自实现，无第三方依赖许可问题）',
    homepage: 'https://en.wikipedia.org/wiki/TOPSIS',
  },
  {
    id: 'entropy-weight',
    name: '熵权法',
    category: 'evaluation',
    summary: '由指标数据的离散程度客观确定权重，常与 TOPSIS 联用。',
    useWhen: ['需要客观权重而非主观打分', '指标数据完整、量纲不一'],
    dataNeeded: ['方案×指标矩阵', '指标正负向与归一化方式'],
    outputs: ['各指标权重', '加权后的评价矩阵'],
    notSuitableFor: ['样本量太少（熵值不稳定）', '指标含大量零值（对数无定义，需平移）'],
    dependencies: ['numpy'],
    entrypoint: '自实现（numpy 向量化，约 25 行）',
    license: '—（自实现）',
    homepage: 'https://en.wikipedia.org/wiki/Entropy_weighting_method',
  },
  {
    id: 'ahp',
    name: '层次分析法 AHP',
    category: 'evaluation',
    summary: '把主观判断构造成判断矩阵并求权重，需通过一致性检验。',
    useWhen: ['指标层级结构清晰', '有专家/经验判断可依据'],
    dataNeeded: ['指标层级结构', '两两比较判断矩阵'],
    outputs: ['各层权重', '一致性比率 CR（需 < 0.1）'],
    notSuitableFor: ['指标过多（判断矩阵阶数高出错率上升）', '完全缺少主观信息时'],
    dependencies: ['numpy'],
    entrypoint: '自实现（特征向量法 + CR 检验，约 50 行）',
    license: '—（自实现）',
    homepage: 'https://en.wikipedia.org/wiki/Analytic_hierarchy_process',
  },
  {
    id: 'grey-relational',
    name: '灰色关联分析',
    category: 'evaluation',
    summary: '在小样本、信息不完全时按序列几何形状的相似度排序各因素的影响程度。',
    useWhen: ['样本量小（<30）不足以做回归', '想判断哪些因素与目标变化趋势最接近'],
    dataNeeded: ['参考序列（目标）与比较序列', '分辨系数 ρ（常取 0.5）'],
    outputs: ['各因素的灰色关联度与排序'],
    notSuitableFor: ['需要量化"影响多少"而非排序', '样本充足时应用回归或方差分析'],
    dependencies: ['numpy'],
    entrypoint: '自实现（无量纲化 + 关联系数，约 30 行）',
    license: '—（自实现）',
    homepage: 'https://en.wikipedia.org/wiki/Grey_relational_analysis',
  },
  {
    id: 'pca',
    name: '主成分分析 PCA',
    category: 'dimensionality',
    summary: '把相关指标压缩成少数互不相关的主成分，用于降维、去共线与可视化。',
    useWhen: ['指标之间高度相关需要合并', '变量多而样本少', '需要在二维/三维里观察样本结构'],
    dataNeeded: ['标准化后的数值矩阵', '保留主成分数（累计方差贡献率阈值）'],
    outputs: ['主成分得分', '载荷矩阵', '方差贡献率与碎石图'],
    notSuitableFor: ['需要保留变量原始含义（主成分是线性和，解释成本高）', '变量间非线性关系'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.decomposition.PCA',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'gmm',
    name: '高斯混合聚类 GMM',
    category: 'clustering',
    summary: '用多个高斯分布的加权和拟合数据，给出样本属于各簇的概率而非硬标签。',
    useWhen: ['簇可以有重叠、需要软分配', '各簇近似椭圆分布'],
    dataNeeded: ['数值特征矩阵', '簇数 K（按 BIC/AIC 选）'],
    outputs: ['各样本的归属概率', '各簇均值与协方差', 'BIC/AIC'],
    notSuitableFor: ['簇形状严重非高斯', '维度很高且样本不足（协方差难估）'],
    dependencies: ['scikit-learn'],
    entrypoint: 'sklearn.mixture.GaussianMixture',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scikit-learn/scikit-learn',
  },
  {
    id: 'prophet',
    name: 'Prophet 趋势季节预测',
    category: 'time-series',
    summary: '把序列拆成趋势、季节与节假日三部分的可加模型，适合有明显周期且含缺失的序列。',
    useWhen: ['序列有强周期性（日/周/年）', '含缺失值或异常点', '需要给出可解释的分量图'],
    dataNeeded: ['两列数据：ds（时间）、y（取值）', '季节周期设置'],
    outputs: ['预测值及不确定性区间', '趋势/季节分量分解图'],
    notSuitableFor: ['极短序列（<2 个周期）', '高频（分钟级）数据'],
    dependencies: ['prophet'],
    entrypoint: 'prophet.Prophet',
    license: 'MIT',
    homepage: 'https://github.com/facebook/prophet',
  },
  {
    id: 'var-model',
    name: 'VAR 向量自回归',
    category: 'time-series',
    summary: '把多个相互影响的时间序列作为一个系统联合建模，可做脉冲响应与格兰杰因果分析。',
    useWhen: ['多个变量随时间互相影响', '需要判断"A 的变化是否领先于 B"'],
    dataNeeded: ['多列等间隔时间序列', '滞后阶数 p（按 AIC/BIC 选）'],
    outputs: ['系数矩阵', '脉冲响应函数', '格兰杰因果检验 p 值'],
    notSuitableFor: ['变量间无动态交互（逐条单变量建模即可）', '序列长度远小于变量数'],
    dependencies: ['statsmodels'],
    entrypoint: 'statsmodels.tsa.api.VAR',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/statsmodels/statsmodels',
  },
  {
    id: 'monte-carlo',
    name: '蒙特卡洛模拟',
    category: 'evaluation',
    summary: '按输入的概率分布大量抽样并统计输出分布，量化结果的不确定性与置信区间。',
    useWhen: ['输入含随机性或测量误差', '需要给出结果的分布而非单点值', '解析传播公式难以推导'],
    dataNeeded: ['各输入变量的分布假设与参数', '模拟次数与随机种子'],
    outputs: ['输出的均值/分位数/置信区间', '输出分布直方图与敏感性排序'],
    notSuitableFor: ['输入几乎是确定值（用灵敏度分析即可）', '单次模拟代价极高且次数不足'],
    dependencies: ['numpy'],
    entrypoint: 'numpy.random.Generator + 自实现（约 40 行）',
    license: '—（自实现）',
    homepage: 'https://en.wikipedia.org/wiki/Monte_Carlo_method',
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap 重采样',
    category: 'evaluation',
    summary: '有放回重采样估计统计量的抽样分布，在样本量小或分布未知时给出置信区间。',
    useWhen: ['样本量小、分布未知', '统计量（如中位数、相关系数）没有现成标准误公式'],
    dataNeeded: ['原始样本', '重采样次数 B（常取 1000–10000）'],
    outputs: ['统计量的标准误与置信区间（百分位法/BCa）'],
    notSuitableFor: ['样本存在强时间相关性（需改用块 bootstrap）', '样本量已足够大且分布已知'],
    dependencies: ['numpy', 'scipy'],
    entrypoint: 'scipy.stats.bootstrap 或自实现重采样',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/scipy/scipy',
  },
  {
    id: 'markov-chain',
    name: '马尔可夫链状态预测',
    category: 'prediction',
    summary: '用状态间转移概率描述系统演化，可预测长期稳态分布与到达时间。',
    useWhen: ['系统可离散成有限状态', '状态转移只依赖当前状态', '关心长期占比或稳态'],
    dataNeeded: ['状态定义', '历史状态序列或转移频次'],
    outputs: ['转移概率矩阵', '稳态分布', 'k 步后的状态分布'],
    notSuitableFor: ['状态划分主观且敏感（需做稳健性检验）', '状态转移依赖更长历史'],
    dependencies: ['numpy'],
    entrypoint: '自实现（频次统计 + 幂迭代求稳态，约 35 行）',
    license: '—（自实现）',
    homepage: 'https://en.wikipedia.org/wiki/Markov_chain',
  },
  {
    id: 'genetic-algorithm',
    name: '遗传算法',
    category: 'optimization',
    summary: '用选择、交叉、变异在离散或混合变量空间搜索优质解，适合组合优化。',
    useWhen: ['决策变量含离散/排列结构（排班、路径、选址）', '解空间大且目标不可导'],
    dataNeeded: ['解的编码方式', '适应度函数', '种群规模、交叉与变异率'],
    outputs: ['最优个体与适应度', '每代最优/平均适应度曲线'],
    notSuitableFor: ['连续光滑问题（梯度或 PSO 更高效）', '需要严格最优性证明'],
    dependencies: ['mealpy'],
    entrypoint: 'mealpy.evolutionary_based.GA.BaseGA',
    license: 'MIT',
    homepage: 'https://github.com/thieu1995/mealpy',
  },
];

export const ALGORITHM_CATEGORY_MESSAGES: Record<AlgorithmCategory, string> = {
  optimization: '优化',
  prediction: '预测',
  'time-series': '时间序列',
  classification: '分类',
  clustering: '聚类',
  dimensionality: '降维',
  evaluation: '评价',
};
