/**
 * Research figure catalogue (科研绘图) for the 扩展 → 模板 page.
 *
 * GENERATED FILE — do not edit by hand. Run `pnpm run figures:catalog`.
 *
 * Two families:
 *
 *  - MathModel figure templates extracted from the installed product, in the
 *    `mathmodel-figure-templates` skill. Ids, titles, categories and layout notes are
 *    the product's own metadata.
 *  - Templates written for this project, under `math_figure/assets/templates/`.
 *
 * Previews are rendered here, not copied from the product:
 *   `pnpm run figures:mathmodel` (MathModel set) and `pnpm run figures:build` (ours).
 */

export type FigureCategory =
  | 'combination'
  | 'distribution'
  | 'flowchart'
  | 'machine-learning'
  | 'model-evaluation'
  | 'spatial'
  | 'ordination'
  | 'composition'
  | 'three-dimensional'
  | 'surface'
  | 'association'
  | 'other'
  | 'attribution'
  | 'feature-report'
  | 'time-series'
  | 'prediction'
;

export interface FigureEntry {
  id: string;
  title: string;
  category: FigureCategory;
  description: string;
  /** Skill that owns the template (both families live in their own skill). */
  skill: 'math-figure' | 'mathmodel-figure-templates';
  /** Path of the script, relative to that skill directory. */
  script: string;
  /** Preview key under src/assets/figures/, empty when none was rendered. */
  preview: string;
  /** Python packages beyond matplotlib the template imports. */
  dependencies: string[];
  available: boolean;
}

export const FIGURE_CATEGORIES: FigureCategory[] = [
  'combination',
  'distribution',
  'flowchart',
  'machine-learning',
  'model-evaluation',
  'spatial',
  'ordination',
  'composition',
  'three-dimensional',
  'surface',
  'association',
  'other',
  'attribution',
  'feature-report',
  'time-series',
  'prediction',
];

/** Display label per category: [Chinese, English]. */
export const FIGURE_CATEGORY_LABELS: Record<FigureCategory, [string, string]> = {
  'combination': ["组合与多面板图", "Combined and multi-panel"],
  'distribution': ["分布、统计与回归矩阵", "Distributions and regression"],
  'flowchart': ["流程图与技术路线图", "Flowcharts and roadmaps"],
  'machine-learning': ["机器学习与特征分析", "Machine learning and features"],
  'model-evaluation': ["模型评价与诊断", "Model evaluation and diagnostics"],
  'spatial': ["响应面与空间网格", "Response surface and spatial grids"],
  'ordination': ["排序与多变量分析", "Ordination and multivariate"],
  'composition': ["组成、排名与多层报告", "Composition and ranking"],
  'three-dimensional': ["三维与同心环形图", "3D and concentric rings"],
  'surface': ["三维曲面、网络与集合", "Surfaces, networks and sets"],
  'association': ["关联、分组矩阵与效应分解", "Association and grouping"],
  'other': ["其他", "Other"],
  'attribution': ["单样本贡献与局部响应", "Per-sample attribution"],
  'feature-report': ["特征贡献与复合效应报告", "Feature contribution reports"],
  'time-series': ["时间序列", "Time series"],
  'prediction': ["预测评价", "Prediction evaluation"],
};

export const FIGURE_CATALOG: FigureEntry[] = [
  {
    id: 'principal-coordinate-map',
    title: "主坐标排序与边缘密度图",
    category: 'ordination',
    description: "中央排序散点与椭圆；顶部和右侧平滑密度；图内分组图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_principal_coordinate_map.py',
    preview: 'mathmodel/principal_coordinate_map',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'redundancy-ordination',
    title: "多编码约束排序图",
    category: 'ordination',
    description: "单排序面板；10支变量箭头；颜色、形状、大小三组独立图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_redundancy_ordination.py',
    preview: 'mathmodel/redundancy_ordination',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'pca-association-network',
    title: "三角相关矩阵与主成分连线图",
    category: 'ordination',
    description: "三角方块相关矩阵与四个主成分节点在同一画布连接；左侧色标及线宽图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_pca_association_network.py',
    preview: 'mathmodel/pca_association_network',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'circular-ranking-bars',
    title: "同心圆弧排名图",
    category: 'composition',
    description: "九条同心圆弧；起点类别、弧内数值与外围角度刻度",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_circular_ranking_bars.py',
    preview: 'mathmodel/circular_ranking_bars',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'horizontal-share-bars',
    title: "横向组成比例与连接带图",
    category: 'composition',
    description: "六条横向百分比堆叠；分区数值、行间连接带和右侧图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_horizontal_share_bars.py',
    preview: 'mathmodel/horizontal_share_bars',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'polar-area-panels',
    title: "九宫格径向扇区分布图",
    category: 'composition',
    description: "3×3九个径向扇区面板；每图14类、百分比外标和逐图色阶图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_polar_area_panels.py',
    preview: 'mathmodel/polar_area_panels',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'radial-stacked-sectors',
    title: "多对象径向堆叠柱图",
    category: 'composition',
    description: "22对象径向堆叠柱；22组成分量、外侧标签、径向刻度与完整颜色图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_radial_stacked_sectors.py',
    preview: 'mathmodel/radial_stacked_sectors',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'ribbon-trajectories-3d',
    title: "多组年度三维条带图",
    category: 'three-dimensional',
    description: "八组逐年有宽度的三维折线条带；三维网格、组名及内置颜色图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_ribbon_trajectories_3d.py',
    preview: 'mathmodel/ribbon_trajectories_3d',
    dependencies: ['scipy', 'cartopy', 'shapely'],
    available: true,
  },
  {
    id: 'waterfall-density-3d',
    title: "多组多阶段三维瀑布峰图",
    category: 'three-dimensional',
    description: "四组配色、每组三阶段共12条瀑布峰；透明填充、阶段标注和图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_waterfall_density_3d.py',
    preview: 'mathmodel/waterfall_density_3d',
    dependencies: ['scipy', 'cartopy', 'shapely'],
    available: true,
  },
  {
    id: 'layered-heatmaps-3d',
    title: "四层三维矩阵热图",
    category: 'three-dimensional',
    description: "四层独立热图平面；三维透视、层级标签和共享色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_layered_heatmaps_3d.py',
    preview: 'mathmodel/layered_heatmaps_3d',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'column-grid-3d',
    title: "规则矩阵三维柱图",
    category: 'three-dimensional',
    description: "10×10三维柱阵；高度与颜色双编码、三轴刻度和独立色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_column_grid_3d.py',
    preview: 'mathmodel/column_grid_3d',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'violin-mean-trends',
    title: "六面板分组小提琴均值矩阵",
    category: 'distribution',
    description: "2×3六面板；每图九组小提琴与箱体；共用连续色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_violin_mean_trends.py',
    preview: 'mathmodel/violin_mean_trends',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'rank-distribution-test',
    title: "两组半小提琴箱线散点检验图",
    category: 'distribution',
    description: "单面板；向外半小提琴、箱体与原始散点叠加；真实检验显著性横线",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_rank_distribution_test.py',
    preview: 'mathmodel/rank_distribution_test',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'polar-estimate-intervals',
    title: "分区径向分组均值与误差图",
    category: 'distribution',
    description: "八个环形分区各四组柱与置信区间；外圈分类色带、数值刻度和中心图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_polar_estimate_intervals.py',
    preview: 'mathmodel/polar_estimate_intervals',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'surface-projection-3d',
    title: "三维响应面与等值底图",
    category: 'surface',
    description: "独立三维线框响应面；底部连续等值投影；竖向色标和完整变量轴",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_surface_projection_3d.py',
    preview: 'mathmodel/surface_projection_3d',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'set-overlap-report',
    title: "四情景集合交叠与贡献条图",
    category: 'surface',
    description: "2×2四组集合交叠图；外部全集边界、七交集计数、图旁集合图例和底部分类色卡",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_set_overlap_report.py',
    preview: 'mathmodel/set_overlap_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'importance-association-report',
    title: "变量重要性与稀疏相关气泡矩阵",
    category: 'distribution',
    description: "40×26稀疏显著性气泡矩阵；26项顶部重要性柱、相关色标和点大小图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_importance_association_report.py',
    preview: 'mathmodel/importance_association_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'time-regression-matrix',
    title: "四变量相关矩阵与年度趋势组合图",
    category: 'distribution',
    description: "左侧4×4相关矩阵：直方密度、散点拟合和统计色块；右侧四层年度回归",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_time_regression_matrix.py',
    preview: 'mathmodel/time_regression_matrix',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'lollipop-effect-grid',
    title: "分层标准化回归系数图",
    category: 'association',
    description: "三类模型各三项系数；分组背景、点大小、虚线连接和右侧图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_lollipop_effect_grid.py',
    preview: 'mathmodel/lollipop_effect_grid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'circular-effect-intervals',
    title: "环形标准化与原始效应比较图",
    category: 'association',
    description: "四簇共12因素；成对环形柱、误差棒、系数环线及底部图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_circular_effect_intervals.py',
    preview: 'mathmodel/circular_effect_intervals',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'correlation-glyph-grid',
    title: "椭圆相关与显著性数字矩阵",
    category: 'association',
    description: "16变量完整矩阵；下三角相关椭圆、上三角数值及显著性、对角变量名",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_correlation_glyph_grid.py',
    preview: 'mathmodel/correlation_glyph_grid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'association-network-heatmap',
    title: "三组相关矩阵与中心响应连线图",
    category: 'association',
    description: "三个角落的三角相关矩阵；中心响应节点与跨面板连线；独立图例和色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_association_network_heatmap.py',
    preview: 'mathmodel/association_network_heatmap',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'split-cohort-correlation',
    title: "双变量同步性三角分割矩阵",
    category: 'association',
    description: "15区域下三角；每格两种条件的半格三角形；分歧色标及双条件坐标标题",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_split_cohort_correlation.py',
    preview: 'mathmodel/split_cohort_correlation',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'regression-uncertainty-scatter',
    title: "误差棒回归与连续着色散点图",
    category: 'association',
    description: "15个误差棒散点；负向回归、零线、右上统计和图内横向连续色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_regression_uncertainty_scatter.py',
    preview: 'mathmodel/regression_uncertainty_scatter',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'fdr-association-map',
    title: "多重检验相关三角热图",
    category: 'association',
    description: "13变量下三角相关色块；每格相关值和FDR显著性；图内显著性图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_fdr_association_map.py',
    preview: 'mathmodel/fdr_association_map',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'grouped-block-correlation',
    title: "分组矩形相关矩阵与排序色带",
    category: 'association',
    description: "20×14分组相关矩阵；左侧三类分组条、顶部色标和逐格显著性",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_grouped_block_correlation.py',
    preview: 'mathmodel/grouped_block_correlation',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'cohort-correlation-bubbles',
    title: "四区域多变量相关气泡图",
    category: 'association',
    description: "四行20变量气泡；大小编码相关强度、颜色编码正负、显著性透明度及侧图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_cohort_correlation_bubbles.py',
    preview: 'mathmodel/cohort_correlation_bubbles',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'interaction-bubble-grid',
    title: "因子交互气泡与数字矩阵",
    category: 'association',
    description: "11×11矩阵；上三角变径气泡、下三角数值、因子标签及统一色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_interaction_bubble_grid.py',
    preview: 'mathmodel/interaction_bubble_grid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'distance-association-network',
    title: "距离关联网络与三角矩阵",
    category: 'association',
    description: "18变量三角方块矩阵；四个右侧距离关联节点；变线宽曲线及色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_distance_association_network.py',
    preview: 'mathmodel/distance_association_network',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'grouped-scatter-matrix',
    title: "分组相关散点与边缘分布矩阵",
    category: 'association',
    description: "5×5组合：4×4分组相关矩阵、右侧四组小提琴、底部四幅直方图及计数柱",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_grouped_scatter_matrix.py',
    preview: 'mathmodel/grouped_scatter_matrix',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'pearson-correlation-map',
    title: "长变量列表稀疏相关矩阵",
    category: 'association',
    description: "30行8列窄长方格矩阵；显著相关方块、顶部斜标签与长行名",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_pearson_correlation_map.py',
    preview: 'mathmodel/pearson_correlation_map',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'petal-correlation-panels',
    title: "四分区扇形相关热图",
    category: 'association',
    description: "四个独立扇形三角相关分区；逐格显著性、外围变量标签、中央图例和底部色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_petal_correlation_panels.py',
    preview: 'mathmodel/petal_correlation_panels',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'grouped-regression-marginals',
    title: "双组回归散点与平滑边缘密度",
    category: 'association',
    description: "金绿双组密集回归散点；顶部与右侧密度；两处组别拟合统计",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_grouped_regression_marginals.py',
    preview: 'mathmodel/grouped_regression_marginals',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'scatter-network-report',
    title: "散点上三角与外部关联网络",
    category: 'association',
    description: "右上5×5散点三角矩阵；对角因子标签；左侧四节点网络及分组图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_scatter_network_report.py',
    preview: 'mathmodel/scatter_network_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'network-profile-report',
    title: "相关网络与共线性径向报告",
    category: 'association',
    description: "左三角相关矩阵连接目标节点；右十一变量径向VIF柱图；完整标签与色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_network_profile_report.py',
    preview: 'mathmodel/network_profile_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-matrix-summary',
    title: "特征贡献热图与汇总条形图",
    category: 'other',
    description: "特征贡献热图与汇总条形图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_matrix_summary.py',
    preview: 'mathmodel/attribution_matrix_summary',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-waterfall',
    title: "单样本贡献瀑布图",
    category: 'attribution',
    description: "十特征单样本瀑布；红蓝箭头条、贡献值、特征取值、基准值和最终预测",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_waterfall.py',
    preview: 'mathmodel/attribution_waterfall',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'grouped-attribution-importance',
    title: "分组贡献条形与蜂群联合图",
    category: 'feature-report',
    description: "17行分组重要性条与蜂群共用排序；顶部浅色标题带、底部横色标和三类指标图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_grouped_attribution_importance.py',
    preview: 'mathmodel/grouped_attribution_importance',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-top-feature-report',
    title: "特征贡献排名与六项依赖图",
    category: 'feature-report',
    description: "左19特征贡献条；右2×3六个贡献依赖散点、平滑拟合与置信带",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_top_feature_report.py',
    preview: 'mathmodel/attribution_top_feature_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-polar-importance',
    title: "镜像贡献排名蜂群与径向占比图",
    category: 'feature-report',
    description: "20特征镜像排名条与蜂群；左下径向占比插图；红蓝渐变及右侧色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_polar_importance.py',
    preview: 'mathmodel/attribution_polar_importance',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'smooth-effect-residual-report',
    title: "十六面板平滑响应等值图",
    category: 'feature-report',
    description: "4×4十六等值面板；统一棕白青色标、白色实虚等值线和每图计算指标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_smooth_effect_residual_report.py',
    preview: 'mathmodel/smooth_effect_residual_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-threshold-report',
    title: "九因子阈值与正负贡献图",
    category: 'feature-report',
    description: "3×3九个阈值图；正负区域填色、蓝色拟合置信带、红色零交点与每图统计",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_threshold_report.py',
    preview: 'mathmodel/attribution_threshold_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'interaction-network',
    title: "密集特征交互环形网络",
    category: 'feature-report',
    description: "18节点完整环网；交互强度控制边色和线宽、节点重要性控制颜色与大小；双独立色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_interaction_network.py',
    preview: 'mathmodel/interaction_network',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-intervals',
    title: "多特征贡献均值区间排名图",
    category: 'feature-report',
    description: "30特征窄长区间图；逐项不同颜色、均值点与横向置信区间、零参考线",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_intervals.py',
    preview: 'mathmodel/attribution_intervals',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'multiresponse-effect-curves',
    title: "四响应贡献回归叠加图",
    category: 'feature-report',
    description: "四响应单面板叠加；散点、非线性拟合及置信带；调整R²和底部分类图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_multiresponse_effect_curves.py',
    preview: 'mathmodel/multiresponse_effect_curves',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'pixel-regression-maps',
    title: "像元主导因子分类图",
    category: 'spatial',
    description: "单幅细密像元主导因子图；四个离散类别及逐类色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_pixel_regression_maps.py',
    preview: 'mathmodel/pixel_regression_maps',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'moving-window-partial-correlation',
    title: "空间网格偏相关热图",
    category: 'spatial',
    description: "单幅空间偏相关栅格；实际控制变量残差相关计算；固定[-1,1]色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_moving_window_partial_correlation.py',
    preview: 'mathmodel/moving_window_partial_correlation',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'spatial-attribution-maps',
    title: "不规则区域主导特征图",
    category: 'spatial',
    description: "白色画布上的不规则区域像元图；两个主导特征类别、区域外掩膜及色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_spatial_attribution_maps.py',
    preview: 'mathmodel/spatial_attribution_maps',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'dual-axis-time-comparison',
    title: "充放电功率与储能时序图",
    category: 'time-series',
    description: "24小时正负渐变功率柱；红色储能折线和右轴；储能由功率累计计算",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_dual_axis_time_comparison.py',
    preview: 'mathmodel/dual_axis_time_comparison',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'pca-variance-report',
    title: "PCA 主成分与方差解释报告",
    category: 'other',
    description: "PCA 主成分与方差解释报告",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_pca_variance_report.py',
    preview: 'mathmodel/pca_variance_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'clustered-rank-correlation',
    title: "双向层次聚类相关热图",
    category: 'ordination',
    description: "24×14矩形秩相关热图；独立行列聚类树、显著性标记、变量标签和色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_clustered_rank_correlation.py',
    preview: 'mathmodel/clustered_rank_correlation',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'ternary-composition',
    title: "三元组成与连续变量气泡图",
    category: 'composition',
    description: "三角网格与三轴刻度；点颜色与大小双编码；独立色标和大小图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_ternary_composition.py',
    preview: 'mathmodel/ternary_composition',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'multiclass-shap-combo',
    title: "多分类 SHAP 柱状图与蜂群图组合图",
    category: 'other',
    description: "多分类 SHAP 柱状图与蜂群图组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_multiclass_shap_combo.py',
    preview: 'mathmodel/multiclass_shap_combo',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'paired-raincloud',
    title: "配对云雨图",
    category: 'other',
    description: "配对云雨图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_paired_raincloud.py',
    preview: 'mathmodel/paired_raincloud',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'cv-roc-ci',
    title: "交叉验证 ROC 曲线与置信区间图",
    category: 'other',
    description: "交叉验证 ROC 曲线与置信区间图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_cv_roc_ci.py',
    preview: 'mathmodel/cv_roc_ci',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'taylor-diagram',
    title: "多模型评价泰勒图",
    category: 'other',
    description: "多模型评价泰勒图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_taylor_diagram.py',
    preview: 'mathmodel/taylor_diagram',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'correlation-pairgrid',
    title: "数据分布、拟合线、置信区间、相关系数组合图",
    category: 'other',
    description: "数据分布、拟合线、置信区间、相关系数组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_correlation_pairgrid.py',
    preview: 'mathmodel/correlation_pairgrid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'prediction-marginal-grid',
    title: "预测值与真实值边缘分布组合图",
    category: 'other',
    description: "预测值与真实值边缘分布组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_prediction_marginal_grid.py',
    preview: 'mathmodel/prediction_marginal_grid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'rf-tpe-surface',
    title: "TPE 优化 RF 模型 3D 曲面图",
    category: 'other',
    description: "TPE 优化 RF 模型 3D 曲面图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_rf_tpe_surface.py',
    preview: 'mathmodel/rf_tpe_surface',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'grouped-corr-split-violin',
    title: "下三角相关矩阵 + 特征分组与半边小提琴图",
    category: 'other',
    description: "下三角相关矩阵 + 特征分组与半边小提琴图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_grouped_corr_split_violin.py',
    preview: 'mathmodel/grouped_corr_split_violin',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'grouped-circular-heatmap',
    title: "分组环形热图",
    category: 'other',
    description: "分组环形热图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_grouped_circular_heatmap.py',
    preview: 'mathmodel/grouped_circular_heatmap',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'urban-park-cooling-combo',
    title: "堆叠图 + 云雨图 + 箱线图组合图",
    category: 'other',
    description: "堆叠图 + 云雨图 + 箱线图组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_urban_park_cooling_combo.py',
    preview: 'mathmodel/urban_park_cooling_combo',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'nature-chord-diagram',
    title: "Nature 风格和弦图",
    category: 'other',
    description: "Nature 风格和弦图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_nature_chord_diagram.py',
    preview: 'mathmodel/nature_chord_diagram',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'land-diurnal-lst-maps',
    title: "昼夜与季节地表温度地图及分布组合图",
    category: 'other',
    description: "昼夜与季节地表温度地图及分布组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_land_diurnal_lst_maps.py',
    preview: 'mathmodel/land_diurnal_lst_maps',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'land-morphology-lst-linear',
    title: "城市形态指标与地表温度线性关系小多图",
    category: 'other',
    description: "城市形态指标与地表温度线性关系小多图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_land_morphology_lst_linear.py',
    preview: 'mathmodel/land_morphology_lst_linear',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'land-morphology-lst-nonlinear',
    title: "城市形态指标与地表温度非线性响应小多图",
    category: 'other',
    description: "城市形态指标与地表温度非线性响应小多图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_land_morphology_lst_nonlinear.py',
    preview: 'mathmodel/land_morphology_lst_nonlinear',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'land-diurnal-feature-importance',
    title: "昼夜特征重要性气泡组合图",
    category: 'other',
    description: "昼夜特征重要性气泡组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_land_diurnal_feature_importance.py',
    preview: 'mathmodel/land_diurnal_feature_importance',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'land-shap-interactions',
    title: "多面板 SHAP 交互效应图",
    category: 'other',
    description: "多面板 SHAP 交互效应图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_land_shap_interactions.py',
    preview: 'mathmodel/land_shap_interactions',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'land-model-prediction-comparison',
    title: "多模型训练与测试预测对比图",
    category: 'other',
    description: "多模型训练与测试预测对比图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_land_model_prediction_comparison.py',
    preview: 'mathmodel/land_model_prediction_comparison',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'sr-weather-model-evaluation-map',
    title: "韩国区域多模型 RMSE、R²、MBE 空间评估地图",
    category: 'other',
    description: "韩国区域多模型 RMSE、R²、MBE 空间评估地图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_sr_weather_model_evaluation_map.py',
    preview: '',
    dependencies: ['scipy', 'cartopy', 'shapely'],
    available: false,
  },
  {
    id: 'sr-weather-downscaling-map',
    title: "约 25 km 到 1 km 的四季气温降尺度地图",
    category: 'other',
    description: "约 25 km 到 1 km 的四季气温降尺度地图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_sr_weather_downscaling_map.py',
    preview: '',
    dependencies: ['scipy', 'cartopy', 'shapely'],
    available: false,
  },
  {
    id: 'karst-es-sdg-sankey',
    title: "生态系统服务—SDG target—SDG 三层桑基/河流图",
    category: 'other',
    description: "生态系统服务—SDG target—SDG 三层桑基/河流图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_karst_es_sdg_sankey.py',
    preview: 'mathmodel/karst_es_sdg_sankey',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'karst-land-use-scenarios',
    title: "三种 SSP 情景土地利用地图与局部放大图",
    category: 'other',
    description: "三种 SSP 情景土地利用地图与局部放大图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_karst_land_use_scenarios.py',
    preview: 'mathmodel/karst_land_use_scenarios',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'karst-ecosystem-services-atlas',
    title: "历史年份与 2035 情景的四类生态系统服务地图图集",
    category: 'other',
    description: "历史年份与 2035 情景的四类生态系统服务地图图集",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_karst_ecosystem_services_atlas.py',
    preview: 'mathmodel/karst_ecosystem_services_atlas',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'karst-es-hotspot-scenarios',
    title: "总生态系统服务与 Getis–Ord Gi* 冷热点情景地图",
    category: 'other',
    description: "总生态系统服务与 Getis–Ord Gi* 冷热点情景地图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_karst_es_hotspot_scenarios.py',
    preview: 'mathmodel/karst_es_hotspot_scenarios',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'esv-grid-zone-scenarios',
    title: "1990–2020 生态系统服务价值五级格网地图",
    category: 'other',
    description: "1990–2020 生态系统服务价值五级格网地图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_esv_grid_zone_scenarios.py',
    preview: 'mathmodel/esv_grid_zone_scenarios',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'esv-local-moran-scenarios',
    title: "1990–2020 四期局部空间自相关聚类地图",
    category: 'other',
    description: "1990–2020 四期局部空间自相关聚类地图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_esv_local_moran_scenarios.py',
    preview: 'mathmodel/esv_local_moran_scenarios',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'landslide-shap-decision-heatmaps',
    title: "双组 SHAP 决策热图与模型输出曲线",
    category: 'other',
    description: "双组 SHAP 决策热图与模型输出曲线",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_landslide_shap_decision_heatmaps.py',
    preview: 'mathmodel/landslide_shap_decision_heatmaps',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'landslide-pdp-interaction-grid',
    title: "单变量 PDP 与双变量交互等值图",
    category: 'other',
    description: "单变量 PDP 与双变量交互等值图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_landslide_pdp_interaction_grid.py',
    preview: 'mathmodel/landslide_pdp_interaction_grid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'biodiversity-global-delta-atlas',
    title: "全球分级地图、纬向剖面与 KDE 分布组合图",
    category: 'other',
    description: "全球分级地图、纬向剖面与 KDE 分布组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_biodiversity_global_delta_atlas.py',
    preview: 'mathmodel/biodiversity_global_delta_atlas',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'biodiversity-global-correlation-atlas',
    title: "全球相关地图、纬向剖面与分区回归系数组合图",
    category: 'other',
    description: "全球相关地图、纬向剖面与分区回归系数组合图",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_biodiversity_global_correlation_atlas.py',
    preview: 'mathmodel/biodiversity_global_correlation_atlas',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'ranked-feature-heatmap',
    title: "排名柱形与贡献热图联合报告",
    category: 'composition',
    description: "上方18项排名柱图与环图；13×18矩阵及右侧两列汇总数值",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_ranked_feature_heatmap.py',
    preview: 'mathmodel/ranked_feature_heatmap',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'radial-cohort-dashboard',
    title: "多队列密集环形评价图",
    category: 'three-dimensional',
    description: "160对象十层同心热图；外圈分类色带、对象文字、外圈数值柱与中心图例",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_radial_cohort_dashboard.py',
    preview: 'mathmodel/radial_cohort_dashboard',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'model-marginal-comparison',
    title: "六模型预测边缘分布与残差矩阵",
    category: 'prediction',
    description: "2×3六模型；每图完整预测散点、顶部渐变直方图、右侧直方图及底部残差条",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_model_marginal_comparison.py',
    preview: 'mathmodel/model_marginal_comparison',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'circular-correlation-rings',
    title: "分组相关系数环形热图",
    category: 'association',
    description: "24因子五层相关数值热环；内圈分组色带、中心图例、外圈名称及开口",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_circular_correlation_rings.py',
    preview: 'mathmodel/circular_correlation_rings',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'effect-marginal-panel-grid',
    title: "十五因子效应与底部直方图矩阵",
    category: 'feature-report',
    description: "3×5十五个效应面板；每图底部直方图、拟合置信带、实际零交点与阈值标注",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_effect_marginal_panel_grid.py',
    preview: 'mathmodel/effect_marginal_panel_grid',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'conditional-effect-histogram',
    title: "条件贡献回归与背景分布图",
    category: 'feature-report',
    description: "背景直方图与彩色贡献散点；两条件回归及置信带、双轴和色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_conditional_effect_histogram.py',
    preview: 'mathmodel/conditional_effect_histogram',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'attribution-dependence-report',
    title: "贡献蜂群与六变量阈值依赖报告",
    category: 'feature-report',
    description: "19特征蜂群叠加灰色重要性条；右侧3×2彩色依赖图，每图阈值、中位线和色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_attribution_dependence_report.py',
    preview: 'mathmodel/attribution_dependence_report',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'response-contour-matrix',
    title: "六对变量响应等值面板",
    category: 'spatial',
    description: "2×3六变量对响应等值图；每图等值线数值、坐标名和独立连续色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_response_contour_matrix.py',
    preview: 'mathmodel/response_contour_matrix',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'spatial-attribution-summary',
    title: "分区长列表贡献分布图",
    category: 'spatial',
    description: "30行空间分组贡献散点；长标签、零线、分组分隔线和连续色标",
    skill: 'mathmodel-figure-templates',
    script: 'scripts/templates/make_spatial_attribution_summary.py',
    preview: 'mathmodel/spatial_attribution_summary',
    dependencies: ['scipy'],
    available: true,
  },
  {
    id: 'roc-cross-validation',
    title: "ROC 交叉验证曲线",
    category: 'model-evaluation',
    description: "per-fold ROC + mean curve + SD band + AUC",
    skill: 'math-figure',
    script: 'assets/templates/model-evaluation/roc_cross_validation.py',
    preview: 'model-evaluation/roc_cross_validation',
    dependencies: [],
    available: true,
  },
  {
    id: 'sensitivity-curves',
    title: "灵敏度弹性曲线",
    category: 'model-evaluation',
    description: "parameter elasticities + the input band where the conclusion holds",
    skill: 'math-figure',
    script: 'assets/templates/model-evaluation/sensitivity_curves.py',
    preview: 'model-evaluation/sensitivity_curves',
    dependencies: [],
    available: true,
  },
  {
    id: 'model-radar',
    title: "多模型雷达图",
    category: 'model-evaluation',
    description: "models across normalised metrics, cost metrics flipped",
    skill: 'math-figure',
    script: 'assets/templates/model-evaluation/model_radar.py',
    preview: 'model-evaluation/model_radar',
    dependencies: [],
    available: true,
  },
  {
    id: 'metric-heatmap',
    title: "模型指标热力图",
    category: 'model-evaluation',
    description: "model x metric matrix, best cell ringed per column",
    skill: 'math-figure',
    script: 'assets/templates/model-evaluation/metric_heatmap.py',
    preview: 'model-evaluation/metric_heatmap',
    dependencies: [],
    available: true,
  },
  {
    id: 'correlation-combined',
    title: "相关性组合图",
    category: 'combination',
    description: "scatter matrix lower triangle + coefficient heatmap upper",
    skill: 'math-figure',
    script: 'assets/templates/combination/correlation_combined.py',
    preview: 'combination/correlation_combined',
    dependencies: [],
    available: true,
  },
  {
    id: 'paired-distributions',
    title: "成对分布图",
    category: 'distribution',
    description: "half violin + box plot + jittered points per group",
    skill: 'math-figure',
    script: 'assets/templates/distribution/paired_distributions.py',
    preview: 'distribution/paired_distributions',
    dependencies: [],
    available: true,
  },
  {
    id: 'data-overview',
    title: "数据体检四联图",
    category: 'distribution',
    description: "missing rate / distributions / correlation / trend",
    skill: 'math-figure',
    script: 'assets/templates/distribution/data_overview.py',
    preview: 'distribution/data_overview',
    dependencies: [],
    available: true,
  },
  {
    id: 'five-band-roadmap',
    title: "五阶段路线图",
    category: 'flowchart',
    description: "five-stage roadmap with an arrow timeline",
    skill: 'math-figure',
    script: 'assets/templates/flowchart/five_band_roadmap.py',
    preview: 'flowchart/five_band_roadmap',
    dependencies: [],
    available: true,
  },
  {
    id: 'three-stage-pipeline',
    title: "三阶段流水线",
    category: 'flowchart',
    description: "inputs / processing / outputs with hand-offs",
    skill: 'math-figure',
    script: 'assets/templates/flowchart/three_stage_pipeline.py',
    preview: 'flowchart/three_stage_pipeline',
    dependencies: [],
    available: true,
  },
  {
    id: 'three-column-framework',
    title: "三栏研究框架",
    category: 'flowchart',
    description: "stage / content / methods in three columns",
    skill: 'math-figure',
    script: 'assets/templates/flowchart/three_column_framework.py',
    preview: 'flowchart/three_column_framework',
    dependencies: [],
    available: true,
  },
  {
    id: 'hierarchical-structure',
    title: "层次结构图",
    category: 'flowchart',
    description: "objective to sub-questions to methods",
    skill: 'math-figure',
    script: 'assets/templates/flowchart/hierarchical_structure.py',
    preview: 'flowchart/hierarchical_structure',
    dependencies: [],
    available: true,
  },
  {
    id: 'horizontal-pipeline',
    title: "横版任务流水线",
    category: 'flowchart',
    description: "left-to-right stages with sub-steps",
    skill: 'math-figure',
    script: 'assets/templates/flowchart/horizontal_pipeline.py',
    preview: 'flowchart/horizontal_pipeline',
    dependencies: [],
    available: true,
  },
  {
    id: 'feature-importance-beeswarm',
    title: "特征重要性蜂群图",
    category: 'machine-learning',
    description: "ranked importance bars + per-sample beeswarm",
    skill: 'math-figure',
    script: 'assets/templates/machine-learning/feature_importance_beeswarm.py',
    preview: 'machine-learning/feature_importance_beeswarm',
    dependencies: [],
    available: true,
  },
  {
    id: 'response-surface-3d',
    title: "三维响应面",
    category: 'spatial',
    description: "response surface with contour floor and optimum",
    skill: 'math-figure',
    script: 'assets/templates/spatial/response_surface_3d.py',
    preview: 'spatial/response_surface_3d',
    dependencies: [],
    available: true,
  },
];

/** Preview images, resolved from the renderer asset folder at build time. */
const PREVIEWS = import.meta.glob<string>('../assets/figures/**/*.png', {
  eager: true,
  import: 'default',
});

/** Thumbnail URL for a catalogue entry, empty string when none was rendered. */
export function figurePreview(entry: FigureEntry): string {
  return entry.preview ? (PREVIEWS[`../assets/figures/${entry.preview}.png`] ?? '') : '';
}

export const AVAILABLE_FIGURE_COUNT = FIGURE_CATALOG.filter((e) => e.available).length;
